{% set name = "gliner" %}
{% set version = "0.2.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gliner-{{ version }}.tar.gz
  sha256: 0afa0aa82f7f31dcc1befb667cb69d1a9760173078d770517381bf7c3c6b378f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - pip
  run:
    - python >={{ python_min }}
    - pytorch >=2.0.0
    - transformers >=4.38.2
    - huggingface_hub >=0.21.4
    - seqeval
    - tqdm
    - onnxruntime
    - sentencepiece

test:
  imports:
    - gliner
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/urchade/GLiNER
  summary: Generalist model for NER (Extract any entity types from texts)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
