{% set name = "gliner" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gliner-{{ version }}.tar.gz
  sha256: 63b2b5044eceba2df919dec6f19868059f94bdde779d8f1f93e4815b9610f04f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0.0
    - pip
  run:
    - python >=3.8
    - pytorch >=2.0.0
    - transformers >=4.38.2
    - huggingface_hub >=0.21.4
    - seqeval
    - tqdm
    - onnxruntime
    - sentencepiece

test:
  imports:
    - gliner
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/urchade/GLiNER
  summary: Generalist model for NER (Extract any entity types from texts)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
